GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/11

###
POST http://localhost:3000/subscribers/11
Content-Type: application/json

{
    "name":"Nitesh Sah",
    "age":26,
    "subscribedToChannel": "subscribed"
}

###
PATCH http://localhost:3000/subscribers/11

###
DELETE http://localhost:3000/subscribers/11